spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
#        商品管理路由
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
#        会员管理路由
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
#        库存管理路由
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
#        第三方服务路由
        - id: thirdparty_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        #        admin路由
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
#          nginx发来的请求
        - id: nginx_product_route
          uri: lb://mall-product
          predicates:
            - Host=huan.mall.com,item.mall.com
#          nginx search
        - id: nginx_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com
#          auth 服务
        - id: nginx_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com